name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: copy branch
        uses: actions/checkout@v4
      -
        name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: keshav_express:v1